### ISSUE TITLE
Cannot update arXiv PDF version

### ISSUE THREAD

**Issue by 0x1orz** [AllanChain/zotero-arxiv-workflow#6]
to update [the arXiv v2 paper](https://arxiv.org/abs/2310.03842v2) to the v3, that does not work. It makes sense that to force update or replace through downloading the latest version.

_Originally posted by @0x1orz in https://github.com/AllanChain/zotero-arxiv-workflow/issues/4#issuecomment-2285728231_

**Comment by AllanChain** [comment]
Can you provide detailed steps to reproduce? This feature assumes that you didn't save a specific version. Check your URL field. It should be https://arxiv.org/abs/2310.03842 instead of https://arxiv.org/abs/2310.03842v2, otherwise the plugin will refuse to update.

To test this feature, you should:
1. Download the PDF from https://arxiv.org/pdf/2310.03842v2 and add it to Zotero. Wait Zotero to find the metadata. This will simulate you added https://arxiv.org/pdf/2310.03842 when the latest version is v2
2. Click "Update arXiv paper" to find updates.

**Comment by 0x1orz** [comment]
Imported into zotero by Microsoft Edeg zotero plugin. then got the metadata, as follow:
<img width="534" alt="image" src="https://github.com/user-attachments/assets/6c438788-2186-4ba4-8972-2b548a2379f8">

Now click the `Update arxiv paper`, then display 'Already up-to-data'. but the paper still is v2, while the latest version is v3.
v2 hash256: 30c63145574d49f8ed92c4771247a49073244b017a7a3c3395856ce3bdbd163f
v3 hash256: 3db370d2f71ba4dfa1274528fd67bb3558cd73bc2465aa2466a2c33e0366d085

**Comment by AllanChain** [comment]
Sorry, I didn't look into the example arXiv paper in detail. The paper 2310.03842 doesn't contain the arXiv ID, and thus it is currently impossible to determine the version.

An ordinary arXiv paper looks like this. Note the arXiv ID on the left.
![Screenshot of attention is all you need](https://github.com/user-attachments/assets/ce5efb2d-7730-4f99-b59a-81e21c98027e)

The message is indeed misleading: the plugin failed to determine the current version and thus is unable to tell whether the online version is newer or not. I'll first improve the message.

Some more questions:
- Do you have many papers like this (i.e. without arXiv ID in PDF) in your field or this is a special case?
- If this is common, do you have any expectation that how the plugin should behave?
  - The plugin currently will not replace the PDF, since you may have some annotations
  - Force update (save the newest PDF separately) does not sound good. You will have a growing number of PDFs.
  - What about downloading the latest PDF and checking hash? I don't know if this is doable in a Zotero plugin.

**Comment by 0x1orz** [comment]
Yeach. the paper is not an ordinary and occasional  arXiv paper.

I checked the hash codes just to discriminate between the offline versions. 'Data Added' of the metadata may be  helpful to determine whether it is out-of-data.  
In common how to  deal with an out-of-data  and annotated  PDF and a latest one, should be needed to manually manager, which is a hard question. Maybe a diff tool for PDF is another one develop requirement.

Anyway, your work is nice and helpful. Thanks.
